FROM node:18-alpine

ARG API_URL
ENV API_URL ${API_URL}

# Faked root tsconfig.json
COPY tsconfig-docker.json tsconfig.json

WORKDIR /app

COPY . /app

RUN npm install
RUN npm run prestart


EXPOSE 8080

CMD ["node", "dist/app.js"]