# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose Action
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
        env:
          DB_HOST: "mysqldb"
          DB_NAME: "Project"
          DB_USERNAME: "ci-user"
          DB_PASSWORD: "temp"
          WEB_APP_URL: "http://localhost:3000"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'product-web-app/package-lock.json'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Integration tests
      run: mvn verify
      working-directory: './product-backend'
